### ISSUE TITLE
Nome do plugin esta violando as diretrizes do repositório do WordPress

### ISSUE THREAD

**Issue by claudiosanches** [claudiosanches/woocommerce-pagarme#111]
Infelizmente não vai ser mais possível manter o nome "WooCommerce Pagar.me" por causa das novas diretrizes do repositório do WordPress, no caso o que viola é o nome começar com `WooCommerce`, qualquer coisa diferente disso já resolve o problema, alguns plugins estão sendo removidos do repositório por causa disso e eu consegui comprar algum tempo para poder atualizar, mas seria legal fazer isso ainda esta semana.
Minha sugestão é usar "Pagar.me for WooCommerce" ou até mesmo "Pagar.me para WooCommerce" logo, entretanto é possível traduzir o nome que vai aparecer no plugin e em https://br.wordpress.org/plugins/woocommerce-pagarme

**Comment by leonampd** [comment]
@claudiosanches tô levando essa issue pra conhecimento de mais pessoas do Pagar.me. Gosto das opções que vc sugeriu mas vou validar com o resto da galera.

**Comment by claudiosanches** [comment]
@leonampd isso é apenas o nome de exibição, a URL vai continuar a mesma, já que nem é possível alterar de qualquer forma, porém com essas novas diretrizes complica, aqui elas se precisar mostrar para alguém: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/#17-plugins-must-respect-trademarks-copyrights-and-project-names

**Comment by murilohns** [comment]
@claudiosanches, onde devemos alterar esse nome? Procurei pelo site do WordPress e não achei nenhuma opção.

1. Essa alteração deve ser feita pelo código?
2. Existe algum padrão que os outros projetos estão seguindo? =]

**Comment by claudiosanches** [comment]
@murilohns 

> Essa alteração deve ser feita pelo código?

No `readme.txt` e no `woocommerce-pagarme.php`, porém mais importante no `readme.txt`, que é o que configura no WordPress.org.

> Existe algum padrão que os outros projetos estão seguindo? =]

Não exatamente, porém como podemos começar com o nome "Pagar.me", acho que deveriamos usar "Pagar.me for WooCommerce".

**Comment by claudiosanches** [comment]
Alguns dos meus plugins que não tenho nenhum contato direto com alguém do método de pagamento, como o do PagSeguro, eu mudei para "Claudio Sanches - PagSeguro for WooCommerce", assim evito confusão de todos os lados, mas aqui podemos usar "Pagar.me" já que vocês também são desenvolvedores do plugin e não vai dar problema pra ninguém.

**Comment by murilohns** [comment]
Show, obrigado por esclarecer minhas dúvidas @claudiosanches,

Podemos mudar pra `Pagar.me for Woocommerce`, como você sugeriu previamente =D
