### ISSUE TITLE
Falha ao finalizar pedido com cartão

### ISSUE THREAD

**Issue by RaphaelBatagini** [claudiosanches/woocommerce-pagarme#119]
Ao tentar finalizar um pedido com cartão estou recebendo as seguintes mensagens de erro:

Nome do portador do cartão está faltando
Data de expiração do cartão está faltando
Número do cartão está faltando
Código de segurança está faltando

Aparentemente nenhum dado do cartão é enviado para a Pagar.me. Enquanto testava em ambiente local imaginei que houvesse alguma restrição relacionada a falta do SSL. Mas o mesmo persiste no site publicado, mesmo em um servidor com SSL configurado.

WC - 4.0.1
Pagar.me for WC - 2.0.17
Brazilian Market on WC - 3.7.2

**Comment by RaphaelBatagini** [comment]
Payload do plugin:
```
string(35) "https://api.pagar.me/1/transactions"
array(3) {
  ["method"]=>
  string(4) "POST"
  ["timeout"]=>
  int(60)
  ["body"]=>
  array(6) {
    ["api_key"]=>
    string(38) "ak_test_um_numero_qualquer"
    ["amount"]=>
    float(4600)
    ["postback_url"]=>
    string(68) "http://fan-force-brasil.local/?wc-api=WC_Pagarme_Credit_Card_Gateway"
    ["customer"]=>
    array(5) {
      ["name"]=>
      string(16) "Raphael Batagini"
      ["email"]=>
      string(23) "raphabatagini@gmail.com"
      ["phone"]=>
      array(2) {
        ["ddd"]=>
        string(2) "11"
        ["number"]=>
        string(9) "954921549"
      }
      ["address"]=>
      array(5) {
        ["street"]=>
        string(15) "Rua Teste"
        ["complementary"]=>
        string(0) ""
        ["zipcode"]=>
        string(8) "03777040"
        ["street_number"]=>
        string(3) "123"
        ["neighborhood"]=>
        string(14) "Jardim Teste"
      }
      ["document_number"]=>
      string(11) "74409228838"
    }
    ["metadata"]=>
    array(1) {
      ["order_number"]=>
      string(2) "65"
    }
    ["split_rules"]=>
    array(2) {
      [0]=>
      array(4) {
        ["recipient_id"]=>
        string(28) "re_hash"
        ["percentage"]=>
        float(20)
        ["liable"]=>
        bool(true)
        ["charge_processing_fee"]=>
        bool(true)
      }
      [1]=>
      array(4) {
        ["recipient_id"]=>
        string(28) "re_hash_2"
        ["percentage"]=>
        float(80)
        ["liable"]=>
        bool(true)
        ["charge_processing_fee"]=>
        bool(true)
      }
    }
  }
}
```

E este é o retorno da Pagar.me:
`{"errors":[{"parameter_name":"card_holder_name","type":"invalid_parameter","message":"Nome do portador do cartão está faltando"},{"parameter_name":"card_expiration_date","type":"invalid_parameter","message":"Data de expiração do cartão está faltando"},{"parameter_name":"card_number","type":"invalid_parameter","message":"Número do cartão está faltando"},{"parameter_name":"card_cvv","type":"invalid_parameter","message":"Código de segurança está faltando"}],"url":"/transactions","method":"post"}`

**Comment by murilohns** [comment]
@RaphaelBatagini, qual navegador você está utilizando?

Consegue informar se aparece algum erro no console do navegador? Se sim, qual?

**Comment by RaphaelBatagini** [comment]
@murilohns acontece tanto no chrome quanto no firefox. Não há nenhum erro no console.

No momento estou utilizando a API de testes da Pagar.me. Poderia ser isto? Versão de 2017.

![Captura de tela de 2020-05-19 11-22-17](https://user-images.githubusercontent.com/9126880/82338369-3419cd00-99c3-11ea-90d0-8fa416528248.png)
![Captura de tela de 2020-05-19 11-21-59](https://user-images.githubusercontent.com/9126880/82338390-39771780-99c3-11ea-9249-a0f0e7b9dd66.png)

**Comment by RaphaelBatagini** [comment]
Obs: Tem este log do mailchimp mas em ambiente local, onde ele não existia, também tive o mesmo erro. Acredito que não seja ele.

**Comment by RaphaelBatagini** [comment]
Obs 2: Acredito que não se trata de nenhum erro de JS que poderia ser exibido no console.
O payload que mandei aqui nos comentários foi extraído com um var_dump logo antes da chamada para a API que dá erro, portanto os dados estão chegando backend.
