### ISSUE TITLE
Falha ao capturar CPF no pagamento com boleto

### ISSUE THREAD

**Issue by RaphaelBatagini** [claudiosanches/woocommerce-pagarme#121]
@claudiosanches vi que já havia um pull request pra isso mas foi rejeitado por falta de evidências do problema. Estou abrindo essa issue na expectativa de tentar ajudar.

Ao realizar pagamento com boleto recebo a mensagem "número do documento está faltando".
Vendo alguns comentários dos colegas aqui no GitHub, decidi investigar o person_type do Extra Checkout Fields for Brazil e cheguei a conclusão que o problema de fato está na tipagem desta informação.

Na linha 288 e 292 do class-wc-pagarme-api.php os condicionais que envolvem $wcbcf_settings['person_type'] estão considerando tipo da variável, string no caso, porém ela está preenchida com inteiros.

Segue alguns prints para exemplificar como debuguei e o resultado:
![screenshot-fanforce com br-2020 05 22-09_12_16](https://user-images.githubusercontent.com/9126880/82667481-58b5b500-9c0e-11ea-8506-2b4778b1254b.png)

Aqui o person type do meu var_dump vindo como inteiro:
![screenshot--2020 05 22-09_14_21](https://user-images.githubusercontent.com/9126880/82667562-7551ed00-9c0e-11ea-871a-9b82a675bf79.png)

Neste caso do exemplo, o sistema todo é bem novo e os plugins estão nas versões mais recentes.
De qualquer forma, os comentários que encontrei por aqui são de 2017, portanto acredito que o problema em si já venha de versões mais antigas.

**Comment by RaphaelBatagini** [comment]
Abri um PR sobre isso aqui:
https://github.com/claudiosanches/woocommerce-pagarme/pull/122

**Comment by murilohns** [comment]
fala @RaphaelBatagini, tudo bem?
Outra forma de corrigir esse bug (caso ainda esteja ocorrendo) é:

1- Acesse as configurações do woocommerce extra checkout fields
2- Altere qualquer campo e salve.
3- Repita o passo 1.
4- Remove a alteração do passo 2 e salve.

Por algum motivo esse passo-a-passo faz com que o CPF passe à ser reconhecido em nosso módulo

**Comment by RaphaelBatagini** [comment]
Tudo certo @murilohns 

Entendo que ao alterar as configurações novamente o plugin deve reenviar o person type como texto para o banco e por isso resolve o problema.

De qualquer forma, meu PR é bem simples (só adicionei uma linha) e evitaria esse tipo de confusão caso fosse aceito.

**Comment by claudiosanches** [comment]
@RaphaelBatagini @murilohns eu acabei de adicionar um novo fix para isso #123, melhor apenas fazer um "cast" no lugar de converter os dados do array, além que por padrão o WordPress já deveria estar usando string para todos os dados, talvez um problema no outro plugin ao instalar ele, entretanto a correção que eu fiz agora deve resolver para todo mundo.

**Comment by RaphaelBatagini** [comment]
@claudiosanches Perfeito!
Faz sentido que o WordPress já deveria forçar essa info como string mas...
Enfim, obrigado pela solução!
