### ISSUE TITLE
Erro quando pagamento é rejeitado, mas depois o Pagar.me Libera

### ISSUE THREAD

**Issue by MrHerickS** [claudiosanches/woocommerce-pagarme#36]
Boa tarde, hoje aconteceu um erro na minha loja:

 - Cliente cria carrinho na loja.
 - Cliente vai para a página de pagamento.
 - Ao tentar efetuar o pagamento via cartão de crédito, o pagamento é negado (provavelmente por ser um valor alto, ou algo assim).
 - Eu liguei para o pagar.me e aprovaram o pagamento e recebi o dinheiro.
 
Só que como os pedidos não aprovados não são salvos no woocommerce, como proceder para ver o que este cliente comprou?

**Comment by claudiosanches** [comment]
Pedido feito é salvo no WooCommerce, menos no caso do checkout pagar.me que para no checkout sem finalizar o pedido.
