### ISSUE TITLE
Erro no pagamento via boleto

### ISSUE THREAD

**Issue by feperrella** [claudiosanches/woocommerce-pagarme#42]
Olá Claudio, estou testando para implementação na loja de um cliente e na tentativa de pagamento por boleto surge dois avisos de Bairro e Número não preenchidos, mesmo ambos endereços estarem preenchidos.

`08-02-2017 @ 21:52:14 - Failed to make the transaction: Array
(
    [headers] => Requests_Utility_CaseInsensitiveDictionary Object
        (
            [data:protected] => Array
                (
                    [date] => Thu, 03 Aug 2017 00:52:15 GMT
                    [content-type] => application/json
                    [content-length] => 287
                    [server] => openresty
                    [access-control-allow-credentials] => true
                    [access-control-allow-headers] => Content-Type, Authorization, X-Requested-With, X-HTTP-Method-Override
                    [access-control-allow-methods] => GET,PUT,POST,DELETE
                    [access-control-allow-origin] => *
                    [charset] => utf-8
                    [x-powered-by] => Express
                    [x-response-time] => 13ms
                )

        )

    [body] => {"errors":[{"parameter_name":"customer[address][neighborhood]","type":"invalid_parameter","message":"bairro está faltando"},{"parameter_name":"customer[address][street_number]","type":"invalid_parameter","message":"número da rua está faltando"}],"url":"/transactions","method":"post"}
    [response] => Array
        (
            [code] => 400
            [message] => Bad Request
        )

    [cookies] => Array
        (
        )

    [filename] => 
    [http_response] => WP_HTTP_Requests_Response Object
        (
            [response:protected] => Requests_Response Object
                (
                    [body] => {"errors":[{"parameter_name":"customer[address][neighborhood]","type":"invalid_parameter","message":"bairro está faltando"},{"parameter_name":"customer[address][street_number]","type":"invalid_parameter","message":"número da rua está faltando"}],"url":"/transactions","method":"post"}
                    [raw] => HTTP/1.1 400 Bad Request
Date: Thu, 03 Aug 2017 00:52:15 GMT
Content-Type: application/json
Content-Length: 287
Connection: close
Server: openresty
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Authorization, X-Requested-With, X-HTTP-Method-Override
Access-Control-Allow-Methods: GET,PUT,POST,DELETE
Access-Control-Allow-Origin: *
Charset: utf-8
X-Powered-By: Express
X-Response-Time: 13ms

{"errors":[{"parameter_name":"customer[address][neighborhood]","type":"invalid_parameter","message":"bairro está faltando"},{"parameter_name":"customer[address][street_number]","type":"invalid_parameter","message":"número da rua está faltando"}],"url":"/transactions","method":"post"}
                    [headers] => Requests_Response_Headers Object
                        (
                            [data:protected] => Array
                                (
                                    [date] => Array
                                        (
                                            [0] => Thu, 03 Aug 2017 00:52:15 GMT
                                        )

                                    [content-type] => Array
                                        (
                                            [0] => application/json
                                        )

                                    [content-length] => Array
                                        (
                                            [0] => 287
                                        )

                                    [server] => Array
                                        (
                                            [0] => openresty
                                        )

                                    [access-control-allow-credentials] => Array
                                        (
                                            [0] => true
                                        )

                                    [access-control-allow-headers] => Array
                                        (
                                            [0] => Content-Type, Authorization, X-Requested-With, X-HTTP-Method-Override
                                        )

                                    [access-control-allow-methods] => Array
                                        (
                                            [0] => GET,PUT,POST,DELETE
                                        )

                                    [access-control-allow-origin] => Array
                                        (
                                            [0] => *
                                        )

                                    [charset] => Array
                                        (
                                            [0] => utf-8
                                        )

                                    [x-powered-by] => Array
                                        (
                                            [0] => Express
                                        )

                                    [x-response-time] => Array
                                        (
                                            [0] => 13ms
                                        )

                                )

                        )

                    [status_code] => 400
                    [protocol_version] => 1.1
                    [success] => 
                    [redirects] => 0
                    [url] => https://api.pagar.me/1/transactions
                    [history] => Array
                        (
                        )

                    [cookies] => Requests_Cookie_Jar Object
                        (
                            [cookies:protected] => Array
                                (
                                )

                        )

                )

            [filename:protected] => 
            [data] => 
            [headers] => 
            [status] => 
        )

)`

**Comment by murilohns** [comment]
Fala @feperrella, esses campos são acessados pelo módulo pagar.me através dos campos disponíveis no plugin [Woocommerce Extra Checkout Fields for Brazil](https://br.wordpress.org/plugins/woocommerce-extra-checkout-fields-for-brazil/)

Se não quiser utilizar esse plugin, você pode visualizar [aqui](https://docs.pagar.me/v2013-03-01/docs/instalando-plugin-pagarme-woocommerce) como o plugin pagar.me acessa esses campos.

**Comment by feperrella** [comment]
Descobri qual era o problema, algo muito peculiar, a checkbox para forçar a atualização do endereço do cliente estava ativa, e neste caso específico o cliente possuia um endereço que não existe no cadastro corretamente, é um CEP para a cidade inteira, então gerava o erro porque atualizava para um endereço inexistente, desativando a opção de forçar a atualização do endereço no checkout resolveu o problema, mantendo os dados preenchidos como o correio aceita, apesar de o cadastro não existir no correio.
