### ISSUE TITLE
Alteração no comportamento de boletos

### ISSUE THREAD

**Issue by murilohns** [claudiosanches/woocommerce-pagarme#43]
Fala @claudiosanches tudo bem?

Recentemente foi lançada uma nova atualização na API pagar.me e os boletos passaram a ter um comportamento diferente.

Antigamente o fluxo de geração de boletos ocorria da seguinte maneira:
_waiting payment_ > _paid_ (se for pago)

Porém os boletos agora devem ser registrados, e no meio deste processo surge um novo status para ele, sendo assim:

_processing_ > _waiting payment_ > _paid_

Sendo:
_processing_ = Boleto sendo registrado junto ao banco. (Boleto não possui URL)
_waiting payment_ = Aguardando pagamento do boleto (Boleto já registrado, com URL)
_paid_ = Boleto pago

ISSUE: Atualmente ao finalizar uma compra de boleto no Woocommerce, o Boleto URL não é exibido. pois há um status a mais em seu ciclo.

Att.

**Comment by claudiosanches** [comment]
Legal, vou ver como alterar isso. Obrigado por reportar.

**Comment by rodrigoPgSup** [comment]
Olá @claudiosanches, tudo bem? 
Só para te ajudar com um pouco mais de detalhes. O comportamento de boletos acontece para todas as novas contas, que estão na última versão de nossa API( para fazer um teste é só criar uma conta na dashboard pagarme). Mais na documentação: docs.pagar.me 

O status final da transaction mais o boleto_url e boleto_barcode vem através de postback para o cliente. 

Muito obrigado pela ajuda Claudio, até.

**Comment by claudiosanches** [comment]
Acabei de lançar a versão 2.0.11 com a correção.
Obrigado.

**Comment by barruda** [comment]
Olá @claudiosanches ... primeiramente parabéns por todo o trabalho que você vem desempenhando... quanto a esta issue... fiz uma instalação do woocommerce + plugin do pagar.me(tudo mais recente possível) e ao utilizar o ambiente de testes quando finalizo um pedido pelo boleto o botão de visualizar o boleto aponta para o site raiz do pagar.me e não para uma url de boleto completa... fiz o teste com o cartão para ver se tinha configurado algo errado e no caso do cartão funcionou bem. Tem alguma dica?

**Comment by murilohns** [comment]
Fala @barruda, tudo bem?

Quando você utiliza a chave de testes este comportamento é o esperado. Aparecer o link para o site do pagar.me é para simular que o boleto foi gerado corretamente, então o módulo está se comportando normalmente.

Se você alterar sua chave para a chave de live, irá notar que irá de fato gerar uma boleto_url.

**Comment by barruda** [comment]
grande @murilohns ... troquei as keys e a informação procede.... funcionou tudo ótimo....

acho que vocês deveriam colocar uma url pra teste tb... para não confundir o usuário....
digo isso de experiência própria... se eu pego um plugin desse e quero testar pra verificar a maturidade da integração e até mesmo do pagar.me e eu vejo um resultado desses eu ficaria com a orelha em pé... neste caso foi diferente pois já estamos em contato com o pagar.me a algum tempo, então eu tive mais boa vontade... espero que você entenda a minha crítica construtiva.

um abraço! e obrigado a todos.

**Comment by murilohns** [comment]
@barruda, antigamente a pagar.me exibia em modo de teste um boleto, para de fato simular que o boleto foi gerado e está tudo certo com a transação. 

Mas houveram alguns problemas que levaram o pagar.me a parar de exibir o boleto dessa forma, e passar a redirecionar para o site https://pagar.me para simular o boleto gerado.

Mas obrigado pelo feedback!

**Comment by barruda** [comment]
@murilohns beleza... talvez somente apontar pra uma página explicando que não tem o boleto com a key de teste já resolveria.
Estou encontrando alguns probleminhas ainda em relação ao boleto... vou tentar abrir tickets aqui e vou te marcar neles.
Um abraço
