### ISSUE TITLE
Loader não centralizado na tela após checkout finalizado

### ISSUE THREAD

**Issue by vitorvmiguel** [claudiosanches/woocommerce-pagarme#47]
### CONTEXTO
Realizando uma integração do plugin woocommerce-pagarme em ambiente de desenvolvimento e realizando algumas transações para a API de testes.

### ATUAL
Ao realizar uma transação aprovada no checkout Pagar.me o modal que cobre a tela durante a transação é finalizado e a tela do carrinho e mostrada novamente com um status disabled, onde nenhuma interação pode ser realizada. Essa tela possui um loader que está fora de centro e a experiência do usuário é prejudicada até que a tela de Pedido Recebido seja exibida (o que leva alguns segundos).

![woocommerce1](https://user-images.githubusercontent.com/24230714/30116795-d29e6c48-92f4-11e7-9d5b-d7823dc06e1e.jpg)

### IDEAL
Não sei se o problema é no tempo de resposta do checkout em si ou se da geração do pedido pelo woocommerce após o pagamento, o ideal seria que ao menos após o modal do checkout ser encerrado que a página fosse posicionada de modo a mostrar o loader e melhorar a experiência do usuário que está aguardando o processamento.

![woocommerce](https://user-images.githubusercontent.com/24230714/30116229-6164107e-92f3-11e7-92d9-66710780d9c6.jpg)

**Comment by claudiosanches** [comment]
Esse loader é do WooCommerce.
