### ISSUE TITLE
status do pedido

### ISSUE THREAD

**Issue by danubiapaiva** [claudiosanches/woocommerce-pagarme#49]
Boa noite Cláudio,

Quando finalizo uma compra, o pedido esta ficando com status de concluído automático.

Pelo que entendi na pagina sua explicação é que isso não deveria ocorrer.

**Comment by murilohns** [comment]
Olá @danubiapaiva, pode me dizer se é uma transação de boleto bancário ou cartão de crédito?

Em caso de cartão de crédito, o pedido deve ser concluído assim que a transação for aprovada pelo banco (em questão de segundos).

**Comment by claudiosanches** [comment]
> Quando finalizo uma compra, o pedido esta ficando com status de concluído automático.

Este plugin é incapaz de fazer isso, que não tem nenhum método que move o status para "concluído", o máximo que pode chegar é "processando".
Me parece que você tem instalado algum plugin para forçar esse comportamento. Já bastante gente reportando coisas similares e sempre usando plugin assim.
