### ISSUE TITLE
Erros no log

### ISSUE THREAD

**Issue by barruda** [claudiosanches/woocommerce-pagarme#51]
estou recebendo MUITOS erros no log na hora do checkout, me parecem somente alerts(apesar do termo error).

Me perdoem se estiver falando bobagem pois sou novo no woocommerce e faz algum tempo que não mexo com PHP... dei uma pesquisada e encontrei que o woocommerce 3.0 exige algumas mudanças dos plugins: https://github.com/woocommerce/woocommerce/issues/14369

Agradeço desde já o tempo despendido e segue um exemplo dos erros que estou recebendo no checkout(independente se o pagamento é feito pelo pagar.me ou não)... posso mandar o log completo se houver necessidade, mas basicamente o que varia de mensagem para mensagem é o atributo do pedido.

Log(usando o pagarme):

[Wed Sep 13 17:58:17.844337 2017] [:error] [pid 1322] [client 177.107.227.193:64740] billing_first_name was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Pagarme_Banking_Ticket_Gateway->process_payment, WC_Pagarme_API->process_regular_payment, WC_Pagarme_API->generate_transaction_data, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: http://52.67.205.209/checkout/

[Wed Sep 13 17:58:17.844500 2017] [:error] [pid 1322] [client 177.107.227.193:64740] billing_last_name was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Pagarme_Banking_Ticket_Gateway->process_payment, WC_Pagarme_API->process_regular_payment, WC_Pagarme_API->generate_transaction_data, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: http://52.67.205.209/checkout/
[Wed Sep 13 17:58:17.844591 2017] [:error] [pid 1322] [client 177.107.227.193:64740] billing_email was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Pagarme_Banking_Ticket_Gateway->process_payment, WC_Pagarme_API->process_regular_payment, WC_Pagarme_API->generate_transaction_data, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: http://52.67.205.209/checkout/

e assim segue para outros atributos do pedido..................

---------------------------------------------------------------------

log quando o meio de pagamento não é o pagarme:
[Wed Sep 13 19:58:12.442660 2017] [:error] [pid 1456] [client 177.107.227.193:50738] payment_method was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_BACS->process_payment, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_on-hold'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_On_Hold_Order->trigger, WC_Email->get_content, WC_Email_Customer_On_Hold_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-on-hold-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_after_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Pagarme_Banking_Ticket_Gateway->email_instructions, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: http://52.67.205.209/checkout/
[Wed Sep 13 19:58:12.442758 2017] [:error] [pid 1456] [client 177.107.227.193:50738] payment_method was called incorrectly. Order properties should not be accessed directly. Backtrace: require('wp-blog-header.php'), require_once('wp-includes/template-loader.php'), do_action('template_redirect'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::do_wc_ajax, do_action('wc_ajax_checkout'), WP_Hook->do_action, WP_Hook->apply_filters, WC_AJAX::checkout, WC_Checkout->process_checkout, WC_Checkout->process_order_payment, WC_Gateway_BACS->process_payment, WC_Order->update_status, WC_Order->save, WC_Order->status_transition, do_action('woocommerce_order_status_pending_to_on-hold'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails::send_transactional_email, do_action_ref_array, WP_Hook->do_action, WP_Hook->apply_filters, WC_Email_Customer_On_Hold_Order->trigger, WC_Email->get_content, WC_Email_Customer_On_Hold_Order->get_content_html, wc_get_template_html, wc_get_template, include('/plugins/woocommerce/templates/emails/customer-on-hold-order.php'), do_action('woocommerce_email_order_details'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Emails->order_details, wc_get_template, include('/plugins/woocommerce/templates/emails/email-order-details.php'), do_action('woocommerce_email_after_order_table'), WP_Hook->do_action, WP_Hook->apply_filters, WC_Pagarme_Credit_Card_Gateway->email_instructions, WC_Abstract_Legacy_Order->__get, wc_doing_it_wrong. This message was added in version 3.0., referer: http://52.67.205.209/checkout/

**Comment by murilohns** [comment]
Fala @barruda, este erro acontece porque você está na versão 2017-08-28 da API pagar.me, e este módulo ainda não suporta essa versão da API, é o mesmo problema que a issue #50.

Pra corrigir isso, sugiro que entre em contato com relacionamento@pagar.me e altere sua versão de API para 2017-07-17.

**Comment by barruda** [comment]
beleza, obrigado Murilo, vou entrar em contato e se o problema persistir comento aqui
