### ISSUE TITLE
Redução do estoque para a forma de Pagamento Boleto Bancário não está funcionando

### ISSUE THREAD

**Issue by barruda** [claudiosanches/woocommerce-pagarme#52]
A redução do estoque não está acontecendo quando o meio de pagamento é boleto bancário... tentei alterar o status do pedido para processando e depois para concluído para ver se daria baixa mas nada aconteceu. Não sei exatamente qual o comportamento esperado para este caso mas me parece um bug mesmo. @murilohns 
Obrigado

**Comment by murilohns** [comment]
Fala @barruda, só é dado baixa no estoque depois que o pedido é pago, isso serve tanto para cartão de crédito quanto para boleto bancário :)

**Comment by barruda** [comment]
Obrigado pela resposta rápida @murilohns ... como eu disse no outro post sou novo no Woocommerce e ainda estou aprendendo tanto o o código quanto o workflow... porém pelo que vi, este comportamento do módulo vai contra o comportamento "padrão" da plataforma não? Por exemplo se eu escolho as formas de pagamento cheque, depósito bancário, dinheiro.... ele já faz a reserva do estoque independente da confirmação de pagamento....

O aviso de pagamento do boleto eh automático pelo Pagar.me? tem um callback pro meu servidor? pq eu não configurei nada disso ainda....

Outra coisa... fica um pouco complicado para eu testar já que não consigo ver boletos no pagar.me ambiente testes... eu teria que emitir um boleto em produção e efetivamente pagar para testar o comportamento? ou tem como eu simular este comportamento tanto no dashboard do pagar.me ou via woocommerce?

Obrigado mais uma vez

**Comment by murilohns** [comment]
Sim @barruda, assim que o boleto for pago é enviado uma notificação para seu sistema com essa informação. O status do pedido é atualizado automaticamente, e é reduzido do estoque os itens referentes à este pedido.

Você pode simular o pagamento de pagamento de boleto através da dashboard.pagar.me, clicando sobre a transação de boleto gerada e após isso clicando em "Simular Pagamento", com isso será enviado um POSTback para seu sistema notificando que a transação foi paga.
Se você estiver rodando em localhost, essa notificação não irá chegar, sendo necessário envia-la manualmente. Você pode fazer isso através do [postman](https://www.getpostman.com/).

As informações necessárias para reenvio da notificação podem ser encontradas em https://api.pagar.me/1/transactions/id_da_transacao/postbacks?api_key=sua_chave_de_api

Nele você encontrará o payload (informações enviadas para o pagar.me, que devem ser inseridas no corpo da requisição post), a postback_url, que se trata do link para qual a notificação será enviada.

**Comment by barruda** [comment]
Beleza @murilohns ... testei aqui e funcionou mto bem!

Somente uma última dúvida... estou em um IP temporário pra testes... quando eu migrar pro domínio oficial eu preciso atualizar alguma coisa como o Pagar.me? ou o ip pro postback eh associado e informado a cada requisição de pagamento?

Obrigado mais uma vez

**Comment by murilohns** [comment]
O POSTback é enviado para o link que é gerado na hora da transação.

Você pode ver o link nessa linha:
https://github.com/claudiosanches/woocommerce-pagarme/blob/master/includes/class-wc-pagarme-api.php#L247

O código é o seguinte: `'postback_url' => WC()->api_request_url( get_class( $this->gateway ) )`

A postback_url ficara parecida com `http://seusite.com/?wc-api=WC_Pagarme_Banking_Ticket_Gateway`

Se você alterar a url de seu site para meunovosite.com, ficará: `http://meunovosite.com/?wc-api=WC_Pagarme_Banking_Ticket_Gateway`, sempre de acordo com a url a qual seu site pertence.

Faz sentido?

**Comment by barruda** [comment]
ótimo! obrigado mais uma vez!

**Comment by valeriosouza** [comment]
Reabrindo o post, não acha errado o boleto só diminuir o estoque depois de ser pago? Estou com vários problemas de estoque negativo por isso.
