### ISSUE TITLE
Tradução pt_BR

### ISSUE THREAD

**Issue by hsribei** [claudiosanches/woocommerce-pagarme#53]
Olá, gostaria de saber se existe tradução do plugin para português brasileiro, onde encontro e como faço para instalar por favor.

Desculpe se é uma pergunta muito básica, já consegui instalar a tradução do WooCommerce em si, mas os campos do Pagar.me continuam em inglês.

Obrigado!

Abs,
Helder

**Comment by hsribei** [comment]
Para facilitar a vida de outros n00bs como eu:

Siga as instruções [aqui](https://docs.woocommerce.com/document/woocommerce-localization/) substituindo "woocommerce" por "woocommerce-pagarme" nas URLs, nomes de diretório e arquivo e tudo deve funcionar. Siga as instruções até antes da seção "Creating custom translations".

Resumindo:

- Vá até o final [desta página](https://translate.wordpress.org/projects/wp-plugins/woocommerce-pagarme/stable/pt-br/default)
- Escolha "Machine Object Message (.mo)" no dropdown da direita
- Clique em "Export"
- Salve como `woocommerce-pagarme-pt_BR.mo`
- No seu site WordPress, crie o diretório `wp-content/languages/woocommerce-pagarme`
- Faça o upload do arquivo acima para este diretório
- Pronto, agora o plugin Pagar.me deve estar em pt_BR.

**Comment by claudiosanches** [comment]
Na verdade não precisa de nada disso.
Basta ir em Atualizações no painel do WordPress e clicar no botão para atualizar as traduções.
É assim que o WordPress instala a tradução de tudo hoje em dia.
