### ISSUE TITLE
URLs diferentes para pagamento concluído com cartão de crédito e boleto emitido

### ISSUE THREAD

**Issue by hsribei** [claudiosanches/woocommerce-pagarme#54]
Atualmente, dois comportamentos distintos levam à mesma URL, `/checkout/order-received/`:

1) Concluir o pagamento com cartão de crédito. A página `/checkout/order-received/` exibe a confirmação de pagamento e (no meu caso de produto baixável) o link para download.

2) Emitir o boleto. A página `/checkout/order-received/` exibe um botão para o download do boleto.

Existe algum jeito de esses dois fluxos levarem a URLs diferentes? Tipo `/order-received/` para o cartão de crédito e `/boleto-emitted/` para o boleto ou algo assim?

Pergunto porque no Google Analytics é importante ter como trackear separadamente o caso "venda concluída" do caso "boleto emitido".

Se não for possível fazer isso como o plugin do modo como está, poderia me dar um direcionamento de onde devo mexer, links pra docs ou palavras-chave pra buscar no google por favor? Agradeceria muito :) Obrigado!

**Comment by hsribei** [comment]
Fiz uma gambiarra que deu certo pro meu caso, mas não acho que é geral o suficiente para ser um pull request. Talvez se mais gente se interessar por customizações de URLs para fins de analytics valha a pena estender no futuro.

Por ora, caso alguém chegue com a mesma dúvida, resolvi do seguinte modo:

https://github.com/hsribei/woocommerce-pagarme/commit/39d5628ffc0020cbbc058f3e1bac0bd3b901d6cf

**Comment by claudiosanches** [comment]
Isso que você esta descrevendo é o comportamento padrão do WooCommerce, qualquer método de pagamento vai direcionar para a mesma URL.
Já o tracking do Google deve ser configurado para agir de forma distinta para cada método da forma que você preferir.

**Comment by claudiosanches** [comment]
O que você fez no código não é necessário de ser feito neste plugin, já que usa um filtro do WooCommerce e você poderia ter feito um plugin apenas para isso.
Assim não vai ter que deixar de atualizar o plugin do Pagar.me.

**Comment by claudiosanches** [comment]
O que você fez no código não é necessário de ser feito neste plugin, já que usa um filtro do WooCommerce e você poderia ter feito um plugin apenas para isso.
Assim não vai ter que deixar de atualizar o plugin do Pagar.me.
