### ISSUE TITLE
Split payments Pagar.me para Dokan

### ISSUE THREAD

**Issue by Luc45** [claudiosanches/woocommerce-pagarme#56]
Boa tarde Cláudio, tranquilo?

Eu gostaria de implementar o Split Payment para Dokan no seu plugin de WooCommerce, e vi que você postou esse código abaixo no fórum de suporte do plugin no Wordpress.org para uma pergunta similar:

```
/**
 * Slip rules for Pagar.me.
 *
 * @param  array    $data  Transacion data.
 * @param  WC_Order $order Order instance.
 * @return array
 */
function wc_pagarme_slip_rules( $data, $order ) {
	$data['split_rules'] = array(
		array(
			'recipient_id'          => 'ID_do_primeiro_recebedor',
			'percentage'            => '50',
			'liable'                => true,
			'charge_processing_fee' => true,
		),
		array(
			'recipient_id'          => 'ID_do_segundo_recebedor',
			'percentage'            => '50',
			'liable'                => true,
			'charge_processing_fee' => true,
		),
	);

	return $data;
}

add_action( 'wc_pagarme_transaction_data', 'wc_pagarme_slip_rules', 10, 2 );
```

No entanto, não consegui identificar quando o hook "wp_pagarme_transaction_data" é chamado. Vi que ele tem um call no método generate_transaction_data(), porém num ciclo completo de checkout ele não passou por esse método.

Minha pergunta é: Quando o hook **wp_pagarme_transaction_data** é chamado?

**Comment by claudiosanches** [comment]
Esse método vai ser chamado quando não é usado o checkout pagar.me, vai ser chamado apenas no standard.
Devo fazer integração com o "Product Vendors" em breve, se quiser mudar do Dokan.

**Comment by rolfzornig** [comment]
Cláudio, existe alguma integração do Pagar.me com o uso de plugins para Marketplaces? Dokan, "Product Vendors", etc...
