### ISSUE TITLE
Novas regras de transação com o protocolo TLS 1.2

### ISSUE THREAD

**Issue by iancom** [claudiosanches/woocommerce-pagarme#67]
Saudações!

O pagar.me vem avisando constantemente sobre a atualização para o protocolo TLS 1.2.
https://docs.pagar.me/docs/atualiza%C3%A7%C3%A3o-tls-12

De acordo com o comunicado, todas as transações utilizando TLS 1.0 e 1.1, a partir das datas expostas serão rejeitadas pela aplicação. É necessário realizar atualização do plugin?

**Comment by claudiosanches** [comment]
Não precisa atualizar o plugin para isso, precisa seu servidor estar atualizado para funcionar com TLS 1.2.
