### ISSUE TITLE
Como podemos melhorar o workflow de desenvolvimento do módulo?

### ISSUE THREAD

**Issue by leonampd** [claudiosanches/woocommerce-pagarme#68]
Olá @claudiosanches , tudo bem?

Aqui é o Leonam. Faço parte do time de integrações/plataformas do Pagar.me. Antes de mais nada gostaria de agradecer todo o suporte que você tem dado à empresa atuando no desenvolvimento/revisão do módulo do Pagar.me para o Woocommerce, porém, estou abrindo essa issue, pois nós gostaríamos de discutir contigo como podemos melhorar o fluxo de desenvolvimento.

Hoje o Woocommerce, está entre as 3 três plataformas mais usadas pelos clientes do Pagar.me, o que é bem expressivo e gera muita demanda em nossa operação no que diz respeito à suporte e também de novas features. Diante disso, temos tido dificuldade em atendê-las dado que nosso time está dependente de você para seguir com implementações e isso tem impactado negativamente nossas entregas. Temos, inclusive, 3 PRs bem importantes abertos que estão aguardando sua revisão sendo que um deles gera muitos tickets no suporte e está aberto há 6 meses. Quanto aos outros dois, um deles atualiza o módulo para a nova versão da nossa API e o segundo, adiciona a possibilidade do tratamento de um novo status, de revisão de pagamento, por parte do lojista.

Sabemos que se trata de um projeto opensource e que não faz sentido você atender de pronto 100% das nossas demandas. No entanto, entendemos que não é escalável para o Pagar.me e por isso, gostaríamos de conversar em conjunto sobre o assunto.

Dado, isso, como você acha que podemos otimizar este cenário? A princípio, pensamos que seria interessante que você nos concedesse acesso de administrador ao repositório. Dessa forma, poderíamos atuar no desenvolvimento com maior liberdade, sem perder sua colaboração sempre que for necessário. O que acha?

Mais uma vez, nós do Pagar.me, agradecemos todo o apoio que você tem dado ao nosso time, e a comunidade como um todo!

Se houver algum e-mail que possamos nos comunicar, nos informe, por favor.

**Comment by brunomosciatti** [comment]
Libera Claudiao - já que voce nao ta ajudando mais <3

**Comment by LauanGuermandi** [comment]
Vai Claudião!! #SubscriptionsJá

**Comment by claudiosanches** [comment]
@leonampd sobre e-mail vocês já tem o meu, os issues aguardando nenhum deles passam por qualquer aprovação por não funcionarem ou estarem fora dos standards do WordPress.
Tudo depende do meu tempo livre, sinta-se livre para forkar o plugin se quiser

**Comment by claudiosanches** [comment]
> Se houver algum e-mail que possamos nos comunicar, nos informe, por favor.

Vocês já tem meu e-mail, provavelmente essa seria melhor uma conversa privada, assim não iria parecer que estão tentando fazer alguma pressão ou tentando me constranger com comentários do tipo "já que voce nao ta ajudando mais <3", seria uma forma bem mais justa de começar esse tipo de conversa.

Isso é um projeto open source que mantenho com carinho e tenho mantido ainda, se eu não fosse mais manter, isso estaria abandonado de vez, ano passado eu tive um monte de problema pessoal na minha vida, como relacionamento de 8 anos acabar e ter que passar por toda um processo de separação... Eu não queria ter que estar tentando lidar com isso em publico, mas não é o jeito, parece que preciso para mostrar meu interesse em ajudar.

> Temos, inclusive, 3 PRs bem importantes abertos que estão aguardando sua revisão sendo que um deles gera muitos tickets no suporte e está aberto há 6 meses. Quanto aos outros dois, um deles atualiza o módulo para a nova versão da nossa API e o segundo, aficionado a possibilidade do tratamento de um novo status, de revisão de pagamento, por parte do lojista.

Para aprovar é simples, envie Pull Requests pequenos, seguindo o coding standards do WordPress, nenhum deles que estão aguardando lá estão seguindo. Tem o PHPCS para ser instalado nesse projeto, vou ver de instruir também pre-commit, quem sabe ajuda mais.

Desta forma vocês vão estar me ajudando revisar isso, sendo que no passado tivemos problemas com falhas de segurança, bugs e outras coisas que foram introduzidas da mesma forma.
Se querem permissões para commitar direto, de boa esses caras aqui já tem:

![screenshot from 2018-06-27 13-18-30](https://user-images.githubusercontent.com/1264099/41986477-9f158e7e-7a0c-11e8-9391-3788b1c43860.png)

Não vi eles commitando direto ainda... mas se quiser trocar quem esta ai, é só falar, entretanto vamos ter que passar por um processo para vocês seguirem isso daqui: https://make.wordpress.org/core/handbook/best-practices/coding-standards/

**Comment by leonampd** [comment]
Oi @claudiosanches

De maneira alguma a abertura dessa issue teve como objetivo te pressionar ou constrager. Como eu disse, você é um dos maiores contribuidores do módulo então, gostaríamos de deixar bem claro que não concordamos com nenhum tipo de cobrança como foi feito acima. Nosso objetivo é juntar forças pra que o módulo continue evoluindo de forma saudável e amigável.

Sobre os pontos que você comentou quanto ao coding standards, nós estamos trabalhando numa adequação, inclusive, pretendemos abrir um novo PR que possa fazer essa verificação de modo automática.

E para que o assunto não prolongue por aqui, vou fechar essa issue e continuamos a conversa por e-mail, ok?
