### ISSUE TITLE
Documentação incorreta de tipo na classe WC_Pagarme_API

### ISSUE THREAD

**Issue by zoiosilva** [claudiosanches/woocommerce-pagarme#72]
## Problema
A documentação da propriedade `$gateway` indica o tipo errado do objeto:
https://github.com/claudiosanches/woocommerce-pagarme/blob/f460567345e92a67d716f08e791cf8e7c8c707c2/includes/class-wc-pagarme-api.php#L22-L27

Além do tipo `WC_Pagarme_Gateway` não existir no repositório, quando o objeto é iniciado no construtor da classe, a instância passada é do tipo `WC_Payment_Gateway`.

## Solução proposta
Trocar o nome do tipo documentado na propriedade `$gateway`, de `WC_Pagarme_Gateway` para `WC_Payment_Gateway`.

**Comment by claudiosanches** [comment]
@zoiosilva essa classe não existe mais, por isso, se quiser pode enviar um Pull Request.
