### ISSUE TITLE
child "type" fails because ["type" is required]

### ISSUE THREAD

**Issue by leomiranda92** [claudiosanches/woocommerce-pagarme#82]
Olá,

Ao finalizar um pedido está aparecendo a notificação de erro que está no título.
Verificando o log aparece essa informação: https://pastebin.com/tVc0c9vd

Já testado apenas com wordpress limpo, woocommerce, pagar.me e extracheckouts e continua o erro.

**Comment by lucas-mdiniz** [comment]
@theoneit dá uma olhada aqui,

https://github.com/claudiosanches/woocommerce-pagarme/issues/50

provavelmente seu problema é com a versão da API do pagar.me

**Comment by theoneit** [comment]
era isso mesmo, pedi pra eles alterarem lá e deu certo, valeu!
