### ISSUE TITLE
Parcelamento default ser disabled

### ISSUE THREAD

**Issue by vagnervst** [claudiosanches/woocommerce-pagarme#85]
Fazer com que o seletor de parcelas tenha como padrão uma option `disabled`, de forma a obrigar o usuário a interagir com o seletor de parcelas para prosseguir com a compra e evitar enganos.

**Comment by rodrigokr** [comment]
Seria muito importante esta simples melhoria, possuo um e-commerce e já tive incontáveis cancelamentos de pedidos devido a isso. E o pior de tudo que o cliente supõe muitas vezes que nós manipulamos a compra em 1 parcela,rsrs.
Agora resta rezar para o Claudio ou alguém ter um tempinho para analisar isso.

**Comment by rodrigokr** [comment]
murilohns como eu faço a tradução do novo texto para escolher as parcelas? No loco translator não consegui.

**Comment by murilohns** [comment]
@rodrigokr, a tradução precisa ser aprovada antes de tudo:
https://translate.wordpress.org/projects/wp-plugins/woocommerce-pagarme/dev/pt-br/default/

Acredito que após isso a tradução estará disponível para o módulo, pode confirmar isso @claudiosanches ?

**Comment by claudiosanches** [comment]
@murilohns acabei de aprovar lá as traduções, colocando vocês como editores de tradução lá também.
