### ISSUE TITLE
Falha na geração de link do boleto

### ISSUE THREAD

**Issue by giselebrugger** [claudiosanches/woocommerce-pagarme#90]
Estou usando o plugin pagar-me 
versão:2.0.12 e
WordPress : 5.1.1
O email enviado ao cliente, após a conclusão da compra, chega  sem o link do boleto.

Eles recebem o e-mail normalmente, com a frase “Pagar boleto bancário” sublinhada, mas sem o link de referência.

“Pagamento
Utilize o seguinte link para visualizar o seu boleto bancário, você pode imprimir e pagar em seu internet banking ou em uma casa lotérica.
Pagar boleto bancário
O seu pedido será processado após recebermos a confirmação do pagamento do boleto bancário.”

**Comment by murilohns** [comment]
Olá @giselebrugger , tudo bem?

Nas configurações de boleto, deixe a opção "Assíncrono" desmarcada, isso deve resolver o problema.

**Comment by giselebrugger** [comment]
Bingoooo @murilohns . Era isso mesmo. Após desmarcar a opção: Assincrono o link enviado no email está OK. Muito obrigada.
