### ISSUE TITLE
Mudança no checkout transparente

### ISSUE THREAD

**Issue by wagnerjaccoud** [claudiosanches/woocommerce-pagarme#91]
Acho que seria uma opção interessante carregar o layout usado no lightbox no lugar do checkout transparente. Creio que poderia ser por meio de um iframe assim como o paypal usa. Desse modo teríamos um checkout mais bonito além de que bem mais fácil para os usuários mas sem a necessidade do modal como é hoje.

**Comment by claudiosanches** [comment]
Não obrigado, mas vamos manter checkout padrão do WooCommerce que você pode personalizar no seu tema.
